# Generated by Django 5.1.7 on 2025-06-11 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schooltable', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='homeroom_teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_teacher', to='userapp.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teacherclasslesson',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltable.schoolclass'),
        ),
        migrations.AddField(
            model_name='teacherclasslesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltable.schoollesson'),
        ),
        migrations.AddField(
            model_name='teacherclasslesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.teacherprofile'),
        ),
    ]
