# Generated by Django 5.1.7 on 2025-06-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooltable', '0002_initial'),
        ('userapp', '0002_teacherprofile_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schooltable.schoolclass')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.studentprofile')),
            ],
        ),
    ]
