# Generated by Django 5.1.7 on 2025-06-18 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooltable', '0003_alter_schoolclass_date_studentclass'),
        ('userapp', '0002_teacherprofile_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='date',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='class_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltable.schoolclass'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.studentprofile'),
        ),
    ]
