# Generated by Django 5.1.7 on 2025-06-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooltable', '0004_alter_schoolclass_date_alter_studentclass_class_num_and_more'),
        ('userapp', '0002_teacherprofile_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='homeroom_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_teacher', to='userapp.teacherprofile'),
        ),
    ]
