# Generated by Django 5.1.7 on 2025-06-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooltable', '0005_alter_schoolclass_homeroom_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
