# Generated by Django 5.1.7 on 2025-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_teacherprofile_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Ученик'), ('Admin', 'Админ'), ('Teacher', 'Учитель')], default='Student', max_length=20, verbose_name='Роль'),
        ),
    ]
