# Generated by Django 5.1.7 on 2025-06-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schooltable', '0005_alter_schoolclass_homeroom_teacher'),
        ('userapp', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quarter', models.CharField(choices=[('1', '1 четверть'), ('2', '2 четверть'), ('3', '3 четверть'), ('4', '4 четверть')], max_length=1)),
                ('mark_type', models.CharField(choices=[('homework', 'Домашнее задание'), ('test', 'Тест'), ('exam', 'Экзамен'), ('verbal_answer', 'Устный ответ'), ('project', 'Проект')], max_length=30)),
                ('value', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schooltable.schoollesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userapp.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userapp.teacherprofile')),
            ],
        ),
    ]
